ARG TARGETPLATFORM
FROM kobeeeef/xdash-alt-base-image:today

WORKDIR /xbot/Alt

COPY non-base-requirements.txt /xbot/Alt/non-base-requirements.txt

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip install --no-cache-dir --prefer-binary XTablesClient&& \
    apt-get install -y build-essential python3-dev && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --prefer-binary -r non-base-requirements.txt && \
    pip install build && \
    pip install scikit-fmm && \
    pip install pyflame && \
    pip install grpcio-tools && \
    pip install grpcio

RUN pip install rknn-toolkit-lite2==2.3.0 --no-cache-dir && \
    pip install pynetworktables

COPY ./src/assets/librknnrt.so /usr/lib/librknnrt.so

WORKDIR /xbot/Alt/src
