name: Update Api Docs

on:
  push:
    branches:
      - main

jobs:
  update-api-docs:
    runs-on: ubuntu-latest
    name: Update API Docs

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install all subpackages
        run: |
          pip install -e Alt-Core
          pip install -e Alt-Cameras
          pip install -e Alt-ObjectLocalization
          pip install -e Alt-Dashboard
          pip install -e Alt-Pathplanning

      - name: Generate New API Docs
        run: python docs/generateapi.py

      # - name: Trigger ReadTheDocs Build (Optional)
      #   run: |
      #     curl -X POST -d "" \
      #       -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
      #       https://readthedocs.org/api/v3/projects/YOUR_PROJECT/versions/latest/builds/
